name: publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install POISE and build docs
      run: |
        python -m pip install --upgrade pip
        python setup.py notopspin
        python -m pip install -r docs/requirements.txt
        cd docs/
        sphinx-build -b dirhtml . dirhtml
        sphinx-build -b latex . latex

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: docs/latex
        root_file: poise.tex

    - name: Copy PDF to dirhtml root
      run: cp docs/latex/poise.pdf docs/dirhtml

    - name: Clone gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Update content
      run: |
        cp -r docs/dirhtml/* gh-pages
        cd gh-pages
        git config --local user.name "GitHub Actions"
        git config --local user.email "<>"
        git add -A
        git commit -m "Update online documentation" || true
        git push
